version: '3.3'

volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: xopeeek/foodgram_backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  frontend:
    image: xopeeek/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db
